name: github action docker
on: [push]
jobs:
  test-running-docker:
    runs-on: ubuntu-latest
    steps:
    - name: cek kode repository
      uses: actions/checkout@v2

    - run: echo "Hallo, selamat datang di Bellshade Docker"

    - name: running testing docker
      run: |
        ls ${{ github.workspace }}
        chmod +x .github/build.sh
        ./.github/build.sh
    - run: echo "status ${{ job.status }}"

