name: docker test with python
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS, ubuntu-latest]
        # untuk menggunakan arsitektur pada arm dan xx86
        arm: [x86, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setting python versi 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependecies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt')}}

      - name: Install Dependencies
        run: |
          echo "Installing required dependencies"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker on macOS
        if: ${{ runner.os.name }} == 'macOS'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install docker


      - name: Python Linting
        run: |
          ls ${{ github.workspace }}
          echo "Running pytest-testinfra tests"
          python .github/testing.py